# -*- mode: ruby -*-
# vi: set ft=ruby :
CLUSTER_VERSION="22"

CONTROLPLANE_NAME= "controlplane-#{CLUSTER_VERSION}"
WORKER_NAME="node-#{CLUSTER_VERSION}-0"

CONTROLPLANE_IP = "172.28.128.20"
WORKER_IP = "172.28.128.2"

CONTROLPLANE_MEMORY_MB = "6144" #6G
WORKER_MEMORY_MB = "6144" #6G

CONTROLPLANE_CPU = "2" #6G
WORKER_CPU = "2" #6G

WORKER_NODE_COUNT = 2

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Master Server
  config.vm.define CONTROLPLANE_NAME do |node|
  
    node.vm.box               = "generic/ubuntu2004"
    node.vm.hostname          = "#{CONTROLPLANE_NAME}.vidbaz.net"

    node.vm.network "private_network", ip: CONTROLPLANE_IP
  
    node.vm.provider :virtualbox do |v|
      v.name    = CONTROLPLANE_NAME
      v.memory  = CONTROLPLANE_MEMORY_MB
      v.cpus    =  CONTROLPLANE_CPU
    end
  
    node.vm.provider :libvirt do |v|
      v.memory  = CONTROLPLANE_MEMORY_MB
      v.nested  = true
      v.cpus    = CONTROLPLANE_CPU
    end
  
    node.vm.provision "shell", path: "bootstrap_controlplane.sh"
  
  end

  # Kubernetes Worker Nodes
  (1..WORKER_NODE_COUNT).each do |i|

    config.vm.define "#{WORKER_NAME}#{i}" do |node|

      node.vm.box               = "generic/ubuntu2004"
      node.vm.hostname          = "#{WORKER_NAME}#{i}.vidbaz.net"

      node.vm.network "private_network", ip: "#{WORKER_IP}#{i}"

      node.vm.provider :virtualbox do |v|
        v.name    = "#{WORKER_NAME}#{i}"
        v.memory  = WORKER_MEMORY_MB
        v.cpus    = WORKER_CPU
      end

      node.vm.provider :libvirt do |v|
        v.memory  = WORKER_MEMORY_MB
        v.nested  = true
        v.cpus    = WORKER_CPU
      end

      node.vm.provision "shell", path: "bootstrap_worker.sh"

    end

  end

end
